apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 962698957678.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 962698957678.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 7eb4e607
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
